#pragma once

#include "pch.h"
#include "joaat.h"

class scrVector
{
public:
	__declspec(align(8)) float x, y, z;

	scrVector() = default;

	scrVector(const float& _x, const float& _y, const float& _z) :
		x(_x), y(_y), z(_z)
	{
	}
}; //Size: 0x0018
static_assert(sizeof(scrVector) == 24);

class __declspec(align(16)) scrVec3N
{
public:
	float x, y, z;
}; //Size: 0x0010
static_assert(sizeof(scrVec3N) == 16);

class scrNativeCallContext
{
public:
	void* m_ReturnValue; //0x0000
	uint32_t m_ArgCount; //0x0008
	uint64_t* m_Args; //0x0010
	uint32_t m_DataCount; //0x0018
	scrVector* m_OutVectors[4]; //0x0020
	scrVec3N m_InVectors[4]; //0x0040
	uint8_t pad[96]; //0x0080
}; //Size: 0x00E0
static_assert(sizeof(scrNativeCallContext) == 0xE0);

typedef int Any;
typedef int Blip;
typedef int Cam;
typedef int Entity;
typedef int FireId;
typedef joaat_t Hash;
typedef int Interior;
typedef int ItemSet;
typedef Entity Object;
typedef Entity Ped;
typedef Object Pickup;
typedef int Player;
typedef Entity ScrHandle;
typedef Entity Vehicle;

typedef int AnimScene;
typedef int PersChar;
typedef int PopZone;
typedef int Prompt;
typedef int PropSet;
typedef int Volume;

typedef scrVector Vector3;

typedef void (*scrNativeHandler)(scrNativeCallContext*);
typedef scrNativeHandler(*GetNativeHandler_t)(uint64_t);

inline std::ostream& operator<<(std::ostream& out, const scrVector& vec)
{
	if (vec.x)
		out << vec.x << 'f';
	else
		out << "0.0f";
	out << ", ";
	if (vec.y)
		out << vec.y << 'f';
	else
		out << "0.0f";
	out << ", ";
	if (vec.z)
		out << vec.z << 'f';
	else
		out << "0.0f";

	return out;
}

enum ePedAttribute
{
	PA_HEALTH,
	PA_STAMINA,
	PA_SPECIALABILITY,
	PA_COURAGE,
	PA_AGILITY,
	PA_SPEED,
	PA_ACCELERATION,
	PA_BONDING,
	SA_HUNGER,
	SA_FATIGUED,
	SA_INEBRIATED,
	SA_POISONED,
	SA_BODYHEAT,
	SA_BODYWEIGHT,
	SA_OVERFED,
	SA_SICKNESS,
	SA_DIRTINESS,
	SA_DIRTINESSHAT,
	MTR_STRENGTH,
	MTR_GRIT,
	MTR_INSTINCT,
	PA_UNRULINESS,
	SA_DIRTINESSSKIN,
	MAX_ATTRIBUTES,
};

enum eWeaponAttachPoint
{
	WEAPON_ATTACH_POINT_INVALID = -1,
	WEAPON_ATTACH_POINT_HAND_PRIMARY = 0,
	WEAPON_ATTACH_POINT_HAND_SECONDARY = 1,
	WEAPON_ATTACH_POINT_PISTOL_R = 2, MAX_HAND_WEAPON_ATTACH_POINTS = 2,
	WEAPON_ATTACH_POINT_PISTOL_L = 3,
	WEAPON_ATTACH_POINT_KNIFE = 4,
	WEAPON_ATTACH_POINT_LASSO = 5,
	WEAPON_ATTACH_POINT_THROWER = 6,
	WEAPON_ATTACH_POINT_BOW = 7,
	WEAPON_ATTACH_POINT_BOW_ALTERNATE = 8,
	WEAPON_ATTACH_POINT_RIFLE = 9,
	WEAPON_ATTACH_POINT_RIFLE_ALTERNATE = 10,
	WEAPON_ATTACH_POINT_LANTERN = 11,
	WEAPON_ATTACH_POINT_TEMP_LANTERN = 12,
	WEAPON_ATTACH_POINT_MELEE = 13, MAX_SYNCED_WEAPON_ATTACH_POINTS = 13,
	WEAPON_ATTACH_POINT_HIP = 14,
	WEAPON_ATTACH_POINT_BOOT = 15,
	WEAPON_ATTACH_POINT_BACK = 16,
	WEAPON_ATTACH_POINT_FRONT = 17,
	WEAPON_ATTACH_POINT_SHOULDERSLING = 18,
	WEAPON_ATTACH_POINT_LEFTBREAST = 19,
	WEAPON_ATTACH_POINT_RIGHTBREAST = 20,
	WEAPON_ATTACH_POINT_LEFTARMPIT = 21,
	WEAPON_ATTACH_POINT_RIGHTARMPIT = 22,
	WEAPON_ATTACH_POINT_LEFTARMPIT_RIFLE = 23,
	WEAPON_ATTACH_POINT_SATCHEL = 24,
	WEAPON_ATTACH_POINT_LEFTARMPIT_BOW = 25,
	WEAPON_ATTACH_POINT_RIGHT_HAND_EXTRA = 26,
	WEAPON_ATTACH_POINT_LEFT_HAND_EXTRA = 27,
	WEAPON_ATTACH_POINT_RIGHT_HAND_AUX = 28,
	MAX_WEAPON_ATTACH_POINTS = 29,
};

enum eAddItemReason : Hash
{
	ADD_REASON_AWARDS = RAGE_JOAAT("ADD_REASON_AWARDS"), // 0xB784AD1E
	ADD_REASON_CREATE_CHARACTER = RAGE_JOAAT("ADD_REASON_CREATE_CHARACTER"), // 0xE2C4FF71
	ADD_REASON_DEBUG = RAGE_JOAAT("ADD_REASON_DEBUG"), // 0x5C05C64D
	ADD_REASON_DEFAULT = RAGE_JOAAT("ADD_REASON_DEFAULT"), // 0x2CD419DC
	ADD_REASON_GET_INVENTORY = RAGE_JOAAT("ADD_REASON_GET_INVENTORY"), // 0xD8188685
	ADD_REASON_INCENTIVE = RAGE_JOAAT("ADD_REASON_INCENTIVE"), // 0x8ADC2E95
	ADD_REASON_LOADOUT = RAGE_JOAAT("ADD_REASON_LOADOUT"), // 0xCA3454E6
	ADD_REASON_LOAD_SAVEGAME = RAGE_JOAAT("ADD_REASON_LOAD_SAVEGAME"), // 0x56212906
	ADD_REASON_LOOTED = RAGE_JOAAT("ADD_REASON_LOOTED"), // 0xCA806A55
	ADD_REASON_MELEE = RAGE_JOAAT("ADD_REASON_MELEE"), // 0x7B9BDCE7
	ADD_REASON_MP_MISSION = RAGE_JOAAT("ADD_REASON_MP_MISSION"), // 0xEC0E0194
	ADD_REASON_NOTIFICATION = RAGE_JOAAT("ADD_REASON_NOTIFICATION"), // 0xC56292D2
	ADD_REASON_PICKUP = RAGE_JOAAT("ADD_REASON_PICKUP"), // 0x1A770E22
	ADD_REASON_PURCHASED = RAGE_JOAAT("ADD_REASON_PURCHASED"), // 0x4A6726C9
	ADD_REASON_SET_AMOUNT = RAGE_JOAAT("ADD_REASON_SET_AMOUNT"), // 0x4504731E
	ADD_REASON_SYNCING = RAGE_JOAAT("ADD_REASON_SYNCING"), // 0x8D4B4FF4
	ADD_REASON_USE_FAILED = RAGE_JOAAT("ADD_REASON_USE_FAILED"), // 0xD385B670
};

enum eRemoveItemReason : Hash
{
	REMOVE_REASON_CLIENT_PURGED = RAGE_JOAAT("REMOVE_REASON_CLIENT_PURGED"), // 0x4A4E94DC
	REMOVE_REASON_COALESCE = RAGE_JOAAT("REMOVE_REASON_COALESCE"), // 0x2ABE393E
	REMOVE_REASON_DEBUG = RAGE_JOAAT("REMOVE_REASON_DEBUG"), // 0xA07362E6
	REMOVE_REASON_DEFAULT = RAGE_JOAAT("REMOVE_REASON_DEFAULT"), // 0xF77DE93D
	REMOVE_REASON_DELETE_CHARACTER = RAGE_JOAAT("REMOVE_REASON_DELETE_CHARACTER"), // 0x20AFBDE9
	REMOVE_REASON_DROPPED = RAGE_JOAAT("REMOVE_REASON_DROPPED"), // 0xEC7FB5D5
	REMOVE_REASON_DUPLICATE = RAGE_JOAAT("REMOVE_REASON_DUPLICATE"), // 0x19047132
	REMOVE_REASON_GIFTED_INCORRECTLY = RAGE_JOAAT("REMOVE_REASON_GIFTED_INCORRECTLY"), // 0x9C4E3829
	REMOVE_REASON_GIVEN = RAGE_JOAAT("REMOVE_REASON_GIVEN"), // 0xAD5377D4
	REMOVE_REASON_INSUFFICIENT_INVENTORY = RAGE_JOAAT("REMOVE_REASON_INSUFFICIENT_INVENTORY"), // 0x518D1AAE
	REMOVE_REASON_ITEM_DOES_NOT_EXIST = RAGE_JOAAT("REMOVE_REASON_ITEM_DOES_NOT_EXIST"), // 0xEAD5D889
	REMOVE_REASON_LOADOUT = RAGE_JOAAT("REMOVE_REASON_LOADOUT"), // 0x1B94E3BA
	REMOVE_REASON_SET_AMOUNT = RAGE_JOAAT("REMOVE_REASON_SET_AMOUNT"), // 0x19D5CFA5
	REMOVE_REASON_SOLD = RAGE_JOAAT("REMOVE_REASON_SOLD"), // 0x76C4B482
	REMOVE_REASON_USED = RAGE_JOAAT("REMOVE_REASON_USED"), // 0x2188E0A3
	REMOVE_REASON_USE_FAILED = RAGE_JOAAT("REMOVE_REASON_USE_FAILED"), // 0x671F9EAD
};

enum eWeaponHash : Hash
{
	WEAPON_UNARMED = RAGE_JOAAT("WEAPON_UNARMED"), // Unarmed

	WEAPON_BOW = RAGE_JOAAT("WEAPON_BOW"), // Bow
	WEAPON_BOW_CHARLES = RAGE_JOAAT("WEAPON_BOW_CHARLES"), // Charles' Bow
	WEAPON_FISHINGROD = RAGE_JOAAT("WEAPON_FISHINGROD"), // Fishing Rod
	WEAPON_KIT_BINOCULARS = RAGE_JOAAT("WEAPON_KIT_BINOCULARS"), // Binoculars
	WEAPON_KIT_CAMERA = RAGE_JOAAT("WEAPON_KIT_CAMERA"), // Camera
	WEAPON_KIT_DETECTOR = RAGE_JOAAT("WEAPON_KIT_DETECTOR"), // Electrostatic Detector
	WEAPON_LASSO = RAGE_JOAAT("WEAPON_LASSO"), // Lasso
	WEAPON_MELEE_ANCIENT_HATCHET = RAGE_JOAAT("WEAPON_MELEE_ANCIENT_HATCHET"), // Stone Hatchet
	WEAPON_MELEE_BROKEN_SWORD = RAGE_JOAAT("WEAPON_MELEE_BROKEN_SWORD"), // Broken Pirate Sword
	WEAPON_MELEE_CLEAVER = RAGE_JOAAT("WEAPON_MELEE_CLEAVER"), // Cleaver
	WEAPON_MELEE_DAVY_LANTERN = RAGE_JOAAT("WEAPON_MELEE_DAVY_LANTERN"), // Lantern
	WEAPON_MELEE_HATCHET = RAGE_JOAAT("WEAPON_MELEE_HATCHET"), // Hatchet
	WEAPON_MELEE_HATCHET_DOUBLE_BIT = RAGE_JOAAT("WEAPON_MELEE_HATCHET_DOUBLE_BIT"), // Double Bit Hatchet
	WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED = RAGE_JOAAT("WEAPON_MELEE_HATCHET_DOUBLE_BIT_RUSTED"), // Rusted Double Bit Hatchet
	WEAPON_MELEE_HATCHET_HEWING = RAGE_JOAAT("WEAPON_MELEE_HATCHET_HEWING"), // Hewing Hatchet
	WEAPON_MELEE_HATCHET_HUNTER = RAGE_JOAAT("WEAPON_MELEE_HATCHET_HUNTER"), // Hunter Hatchet
	WEAPON_MELEE_HATCHET_HUNTER_RUSTED = RAGE_JOAAT("WEAPON_MELEE_HATCHET_HUNTER_RUSTED"), // Rusted Hunter Hatchet
	WEAPON_MELEE_HATCHET_MELEEONLY = RAGE_JOAAT("WEAPON_MELEE_HATCHET_MELEEONLY"), // Hatchet (Melee Only)
	WEAPON_MELEE_HATCHET_VIKING = RAGE_JOAAT("WEAPON_MELEE_HATCHET_VIKING"), // Viking Hatchet
	WEAPON_MELEE_KNIFE = RAGE_JOAAT("WEAPON_MELEE_KNIFE"), // Hunting Knife
	WEAPON_MELEE_KNIFE_BEAR = RAGE_JOAAT("WEAPON_MELEE_KNIFE_BEAR"), // Antler Knife
	WEAPON_MELEE_KNIFE_BILL = RAGE_JOAAT("WEAPON_MELEE_KNIFE_BILL"), // Bill's Knife
	WEAPON_MELEE_KNIFE_CHARLES = RAGE_JOAAT("WEAPON_MELEE_KNIFE_CHARLES"), // Charles' Knife
	WEAPON_MELEE_KNIFE_CIVIL_WAR = RAGE_JOAAT("WEAPON_MELEE_KNIFE_CIVIL_WAR"), // Civil War Knife
	WEAPON_MELEE_KNIFE_DUTCH = RAGE_JOAAT("WEAPON_MELEE_KNIFE_DUTCH"), // Dutch's Knife
	WEAPON_MELEE_KNIFE_HOSEA = RAGE_JOAAT("WEAPON_MELEE_KNIFE_HOSEA"), // Hosea's Knife
	WEAPON_MELEE_KNIFE_JAWBONE = RAGE_JOAAT("WEAPON_MELEE_KNIFE_JAWBONE"), // Jawbone Knife
	WEAPON_MELEE_KNIFE_JAVIER = RAGE_JOAAT("WEAPON_MELEE_KNIFE_JAVIER"), // Javier's Knife
	WEAPON_MELEE_KNIFE_JOHN = RAGE_JOAAT("WEAPON_MELEE_KNIFE_JOHN"), // John's Knife
	WEAPON_MELEE_KNIFE_KIERAN = RAGE_JOAAT("WEAPON_MELEE_KNIFE_KIERAN"), // Kieran's Knife
	WEAPON_MELEE_KNIFE_LENNY = RAGE_JOAAT("WEAPON_MELEE_KNIFE_LENNY"), // Lenny's Knife
	WEAPON_MELEE_KNIFE_MICAH = RAGE_JOAAT("WEAPON_MELEE_KNIFE_MICAH"), // Micah's Knife
	WEAPON_MELEE_KNIFE_MINER = RAGE_JOAAT("WEAPON_MELEE_KNIFE_MINER"), // Wide-Blade Knife
	WEAPON_MELEE_KNIFE_SADIE = RAGE_JOAAT("WEAPON_MELEE_KNIFE_SADIE"), // Sadie's Knife
	WEAPON_MELEE_KNIFE_SEAN = RAGE_JOAAT("WEAPON_MELEE_KNIFE_SEAN"), // Sean's Knife
	WEAPON_MELEE_KNIFE_UNCLE = RAGE_JOAAT("WEAPON_MELEE_KNIFE_UNCLE"), // Uncle's Knife
	WEAPON_MELEE_KNIFE_VAMPIRE = RAGE_JOAAT("WEAPON_MELEE_KNIFE_VAMPIRE"), // Ornate Dagger
	WEAPON_MELEE_LANTERN = RAGE_JOAAT("WEAPON_MELEE_LANTERN"), // Old Lantern
	WEAPON_MELEE_LANTERN_ELECTRIC = RAGE_JOAAT("WEAPON_MELEE_LANTERN_ELECTRIC"), // Electric Lantern
	WEAPON_MELEE_MACHETE = RAGE_JOAAT("WEAPON_MELEE_MACHETE"), // Machete
	WEAPON_MELEE_TORCH = RAGE_JOAAT("WEAPON_MELEE_TORCH"), // Torch
	WEAPON_MELEE_TORCH_CROWD = RAGE_JOAAT("WEAPON_MELEE_TORCH_CROWD"), // Torch
	WEAPON_MOONSHINEJUG = RAGE_JOAAT("WEAPON_MOONSHINEJUG"), // Moonshine Jug
	WEAPON_PISTOL_M1899 = RAGE_JOAAT("WEAPON_PISTOL_M1899"), // M1899 Pistol
	WEAPON_PISTOL_MAUSER = RAGE_JOAAT("WEAPON_PISTOL_MAUSER"), // Mauser Pistol
	WEAPON_PISTOL_MAUSER_DRUNK = RAGE_JOAAT("WEAPON_PISTOL_MAUSER_DRUNK"), // Midnight's Pistol
	WEAPON_PISTOL_SEMIAUTO = RAGE_JOAAT("WEAPON_PISTOL_SEMIAUTO"), // Semi-Automatic Pistol
	WEAPON_PISTOL_VOLCANIC = RAGE_JOAAT("WEAPON_PISTOL_VOLCANIC"), // Volcanic Pistol
	WEAPON_REPEATER_CARBINE = RAGE_JOAAT("WEAPON_REPEATER_CARBINE"), // Carbine Repeater
	WEAPON_REPEATER_CARBINE_SADIE = RAGE_JOAAT("WEAPON_REPEATER_CARBINE_SADIE"), // Sadie's Carbine Repeater
	WEAPON_REPEATER_EVANS = RAGE_JOAAT("WEAPON_REPEATER_EVANS"), // Evans Repeater
	WEAPON_REPEATER_HENRY = RAGE_JOAAT("WEAPON_REPEATER_HENRY"), // Litchfield Repeater
	WEAPON_REPEATER_WINCHESTER = RAGE_JOAAT("WEAPON_REPEATER_WINCHESTER"), // Lancaster Repeater
	WEAPON_REPEATER_WINCHESTER_JOHN = RAGE_JOAAT("WEAPON_REPEATER_WINCHESTER_JOHN"), // John's Lancaster Repeater
	WEAPON_REVOLVER_CATTLEMAN = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN"), // Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_DUALWIELD = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_DUALWIELD"), // Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_HOSEA = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_HOSEA"), // Hosea's Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_HOSEA_DUALWIELD = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_HOSEA_DUALWIELD"), // Hosea's Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_JOHN = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_JOHN"), // John's Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_KIERAN = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_KIERAN"), // Kieran's Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_LENNY = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_LENNY"), // Lenny's Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_MEXICAN = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_MEXICAN"), // Flaco's Revolver
	WEAPON_REVOLVER_CATTLEMAN_PIG = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_PIG"), // Granger's Revolver
	WEAPON_REVOLVER_CATTLEMAN_SADIE = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_SADIE"), // Sadie's Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_SADIE_DUALWIELD = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_SADIE_DUALWIELD"), // Sadie's Cattleman Revolver
	WEAPON_REVOLVER_CATTLEMAN_SEAN = RAGE_JOAAT("WEAPON_REVOLVER_CATTLEMAN_SEAN"), // Sean's Cattleman Revolver
	WEAPON_REVOLVER_DOUBLEACTION = RAGE_JOAAT("WEAPON_REVOLVER_DOUBLEACTION"), // Double-Action Revolver
	WEAPON_REVOLVER_DOUBLEACTION_DUALWIELD = RAGE_JOAAT("WEAPON_REVOLVER_DOUBLEACTION_DUALWIELD"), // Double-Action Revolver
	WEAPON_REVOLVER_DOUBLEACTION_EXOTIC = RAGE_JOAAT("WEAPON_REVOLVER_DOUBLEACTION_EXOTIC"), // Algernon's Revolver
	WEAPON_REVOLVER_DOUBLEACTION_GAMBLER = RAGE_JOAAT("WEAPON_REVOLVER_DOUBLEACTION_GAMBLER"), // High Roller Revolver
	WEAPON_REVOLVER_DOUBLEACTION_JAVIER = RAGE_JOAAT("WEAPON_REVOLVER_DOUBLEACTION_JAVIER"), // Javier's Double-Action Revolver
	WEAPON_REVOLVER_DOUBLEACTION_MICAH = RAGE_JOAAT("WEAPON_REVOLVER_DOUBLEACTION_MICAH"), // Micah's Revolver
	WEAPON_REVOLVER_DOUBLEACTION_MICAH_DUALWIELD = RAGE_JOAAT("WEAPON_REVOLVER_DOUBLEACTION_MICAH_DUALWIELD"), // Micah's Revolver
	WEAPON_REVOLVER_LEMAT = RAGE_JOAAT("WEAPON_REVOLVER_LEMAT"), // LeMat Revolver
	WEAPON_REVOLVER_SCHOFIELD = RAGE_JOAAT("WEAPON_REVOLVER_SCHOFIELD"), // Schofield Revolver
	WEAPON_REVOLVER_SCHOFIELD_BILL = RAGE_JOAAT("WEAPON_REVOLVER_SCHOFIELD_BILL"), // Bill's Schofield Revolver
	WEAPON_REVOLVER_SCHOFIELD_CALLOWAY = RAGE_JOAAT("WEAPON_REVOLVER_SCHOFIELD_CALLOWAY"), // Calloway's Revolver
	WEAPON_REVOLVER_SCHOFIELD_DUALWIELD = RAGE_JOAAT("WEAPON_REVOLVER_SCHOFIELD_DUALWIELD"), // Schofield Revolver
	WEAPON_REVOLVER_SCHOFIELD_DUTCH = RAGE_JOAAT("WEAPON_REVOLVER_SCHOFIELD_DUTCH"), // Dutch's Schofield Revolver
	WEAPON_REVOLVER_SCHOFIELD_DUTCH_DUALWIELD = RAGE_JOAAT("WEAPON_REVOLVER_SCHOFIELD_DUTCH_DUALWIELD"), // Dutch's Schofield Revolver
	WEAPON_REVOLVER_SCHOFIELD_GOLDEN = RAGE_JOAAT("WEAPON_REVOLVER_SCHOFIELD_GOLDEN"), // Otis Miller's Revolver
	WEAPON_REVOLVER_SCHOFIELD_UNCLE = RAGE_JOAAT("WEAPON_REVOLVER_SCHOFIELD_UNCLE"), // Uncle's Schofield Revolver
	WEAPON_RIFLE_BOLTACTION = RAGE_JOAAT("WEAPON_RIFLE_BOLTACTION"), // Bolt Action Rifle
	WEAPON_RIFLE_BOLTACTION_BILL = RAGE_JOAAT("WEAPON_RIFLE_BOLTACTION_BILL"), // Bill's Bolt Action Rifle
	WEAPON_RIFLE_SPRINGFIELD = RAGE_JOAAT("WEAPON_RIFLE_SPRINGFIELD"), // Springfield Rifle
	WEAPON_RIFLE_VARMINT = RAGE_JOAAT("WEAPON_RIFLE_VARMINT"), // Varmint Rifle
	WEAPON_SHOTGUN_DOUBLEBARREL = RAGE_JOAAT("WEAPON_SHOTGUN_DOUBLEBARREL"), // Double-Barreled Shotgun
	WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC = RAGE_JOAAT("WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC"), // Rare Shotgun
	WEAPON_SHOTGUN_DOUBLEBARREL_UNCLE = RAGE_JOAAT("WEAPON_SHOTGUN_DOUBLEBARREL_UNCLE"), // Uncle's Double-Barreled Shotgun
	WEAPON_SHOTGUN_PUMP = RAGE_JOAAT("WEAPON_SHOTGUN_PUMP"), // Pump-Action Shotgun
	WEAPON_SHOTGUN_REPEATING = RAGE_JOAAT("WEAPON_SHOTGUN_REPEATING"), // Repeating Shotgun
	WEAPON_SHOTGUN_SAWEDOFF = RAGE_JOAAT("WEAPON_SHOTGUN_SAWEDOFF"), // Sawed-Off Shotgun
	WEAPON_SHOTGUN_SAWEDOFF_CHARLES = RAGE_JOAAT("WEAPON_SHOTGUN_SAWEDOFF_CHARLES"), // Charles' Sawed-Off Shotgun
	WEAPON_SHOTGUN_SEMIAUTO = RAGE_JOAAT("WEAPON_SHOTGUN_SEMIAUTO"), // Semi-Auto Shotgun
	WEAPON_SHOTGUN_SEMIAUTO_HOSEA = RAGE_JOAAT("WEAPON_SHOTGUN_SEMIAUTO_HOSEA"), // Hosea's Semi-Auto Shotgun
	WEAPON_SNIPERRIFLE_CARCANO = RAGE_JOAAT("WEAPON_SNIPERRIFLE_CARCANO"), // Carcano Rifle
	WEAPON_SNIPERRIFLE_ROLLINGBLOCK = RAGE_JOAAT("WEAPON_SNIPERRIFLE_ROLLINGBLOCK"), // Rolling Block Rifle
	WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC = RAGE_JOAAT("WEAPON_SNIPERRIFLE_ROLLINGBLOCK_EXOTIC"), // Rare Rolling Block Rifle
	WEAPON_SNIPERRIFLE_ROLLINGBLOCK_LENNY = RAGE_JOAAT("WEAPON_SNIPERRIFLE_ROLLINGBLOCK_LENNY"), // Lenny's Rolling Block Rifle
	WEAPON_THROWN_DYNAMITE = RAGE_JOAAT("WEAPON_THROWN_DYNAMITE"), // Dynamite
	WEAPON_THROWN_MOLOTOV = RAGE_JOAAT("WEAPON_THROWN_MOLOTOV"), // Fire Bottle
	WEAPON_THROWN_THROWING_KNIVES = RAGE_JOAAT("WEAPON_THROWN_THROWING_KNIVES"), // Throwing Knife
	WEAPON_THROWN_THROWING_KNIVES_JAVIER = RAGE_JOAAT("WEAPON_THROWN_THROWING_KNIVES_JAVIER"), // Javier's Throwing Knife
	WEAPON_THROWN_TOMAHAWK = RAGE_JOAAT("WEAPON_THROWN_TOMAHAWK"), // Tomahawk
	WEAPON_THROWN_TOMAHAWK_ANCIENT = RAGE_JOAAT("WEAPON_THROWN_TOMAHAWK_ANCIENT"), // Ancient Tomahawk
	WEAPON_THROWN_TOMAHAWK_MELEEONLY = RAGE_JOAAT("WEAPON_THROWN_TOMAHAWK_MELEEONLY"), // Tomahawk (Melee Only)
	WEAPON_TURRET_CANNON = RAGE_JOAAT("WEAPON_TURRET_CANNON"), // Breach Cannon
	WEAPON_TURRET_GATLING = RAGE_JOAAT("WEAPON_TURRET_GATLING"), // Gatling Gun
	WEAPON_TURRET_MAXIM = RAGE_JOAAT("WEAPON_TURRET_MAXIM"), // Maxim Gun
	WEAPON_TURRET_REVOLVING_CANNON = RAGE_JOAAT("WEAPON_TURRET_REVOLVING_CANNON"), // Revolving Cannon
};

enum eAmmoType : Hash
{
	AMMO_22 = RAGE_JOAAT("AMMO_22"), // Rifle Cartridges - Varmint
	AMMO_22_TRANQUILIZER = RAGE_JOAAT("AMMO_22_TRANQUILIZER"), // Rifle Cartridges - Sedative Varmint
	AMMO_ARROW = RAGE_JOAAT("AMMO_ARROW"), // Arrows
	AMMO_ARROW_DYNAMITE = RAGE_JOAAT("AMMO_ARROW_DYNAMITE"), // Arrow - Dynamite
	AMMO_ARROW_FIRE = RAGE_JOAAT("AMMO_ARROW_FIRE"), // Arrow - Fire
	AMMO_ARROW_IMPROVED = RAGE_JOAAT("AMMO_ARROW_IMPROVED"), // Arrow - Improved
	AMMO_ARROW_POISON = RAGE_JOAAT("AMMO_ARROW_POISON"), // Arrow - Poison
	AMMO_ARROW_SMALL_GAME = RAGE_JOAAT("AMMO_ARROW_SMALL_GAME"), // Arrow - Small Game
	AMMO_ARROW_TRACKING = RAGE_JOAAT("AMMO_ARROW_TRACKING"), // Arrow - Tracking
	AMMO_DYNAMITE = RAGE_JOAAT("AMMO_DYNAMITE"), // Dynamite
	AMMO_DYNAMITE_VOLATILE = RAGE_JOAAT("AMMO_DYNAMITE_VOLATILE"), // Dynamite - Volatile
	AMMO_HATCHET = RAGE_JOAAT("AMMO_HATCHET"), // Hatchet
	AMMO_HATCHET_ANCIENT = RAGE_JOAAT("AMMO_HATCHET_ANCIENT"), // Stone Hatchet
	AMMO_HATCHET_CLEAVER = RAGE_JOAAT("AMMO_HATCHET_CLEAVER"), // Cleaver
	AMMO_HATCHET_DOUBLE_BIT = RAGE_JOAAT("AMMO_HATCHET_DOUBLE_BIT"), // Double Bit Hatchet
	AMMO_HATCHET_DOUBLE_BIT_RUSTED = RAGE_JOAAT("AMMO_HATCHET_DOUBLE_BIT_RUSTED"), // Rusted Double Bit Hatchet
	AMMO_HATCHET_HEWING = RAGE_JOAAT("AMMO_HATCHET_HEWING"), // Hewing Hatchet
	AMMO_HATCHET_HUNTER = RAGE_JOAAT("AMMO_HATCHET_HUNTER"), // Hunter Hatchet
	AMMO_HATCHET_HUNTER_RUSTED = RAGE_JOAAT("AMMO_HATCHET_HUNTER_RUSTED"), // Rusted Hunter Hatchet
	AMMO_HATCHET_VIKING = RAGE_JOAAT("AMMO_HATCHET_VIKING"), // Viking Hatchet
	AMMO_LASSO = RAGE_JOAAT("AMMO_LASSO"), // Lasso Ammo
	AMMO_MOLOTOV = RAGE_JOAAT("AMMO_MOLOTOV"), // Fire Bottle
	AMMO_MOLOTOV_VOLATILE = RAGE_JOAAT("AMMO_MOLOTOV_VOLATILE"), // Fire Bottle - Volatile
	AMMO_MOONSHINEJUG = RAGE_JOAAT("AMMO_MOONSHINEJUG"), // Moonshine
	AMMO_PISTOL = RAGE_JOAAT("AMMO_PISTOL"), // Pistol Cartridges - Regular
	AMMO_PISTOL_EXPRESS = RAGE_JOAAT("AMMO_PISTOL_EXPRESS"), // Pistol Cartridges - Express
	AMMO_PISTOL_EXPRESS_EXPLOSIVE = RAGE_JOAAT("AMMO_PISTOL_EXPRESS_EXPLOSIVE"), // Pistol Cartridges - Explosive
	AMMO_PISTOL_HIGH_VELOCITY = RAGE_JOAAT("AMMO_PISTOL_HIGH_VELOCITY"), // Pistol Cartridges - High Velocity
	AMMO_PISTOL_SPLIT_POINT = RAGE_JOAAT("AMMO_PISTOL_SPLIT_POINT"), // Pistol Cartridges - Split Point
	AMMO_REPEATER = RAGE_JOAAT("AMMO_REPEATER"), // Repeater Cartridges - Regular
	AMMO_REPEATER_EXPRESS = RAGE_JOAAT("AMMO_REPEATER_EXPRESS"), // Repeater Cartridges - Express
	AMMO_REPEATER_EXPRESS_EXPLOSIVE = RAGE_JOAAT("AMMO_REPEATER_EXPRESS_EXPLOSIVE"), // Repeater Cartridges - Explosive
	AMMO_REPEATER_HIGH_VELOCITY = RAGE_JOAAT("AMMO_REPEATER_HIGH_VELOCITY"), // Repeater Cartridges - High Velocity
	AMMO_REPEATER_SPLIT_POINT = RAGE_JOAAT("AMMO_REPEATER_SPLIT_POINT"), // Repeater Cartridges - Split Point
	AMMO_REVOLVER = RAGE_JOAAT("AMMO_REVOLVER"), // Revolver Cartridges - Regular
	AMMO_REVOLVER_EXPRESS = RAGE_JOAAT("AMMO_REVOLVER_EXPRESS"), // Revolver Cartridges - Express
	AMMO_REVOLVER_EXPRESS_EXPLOSIVE = RAGE_JOAAT("AMMO_REVOLVER_EXPRESS_EXPLOSIVE"), // Revolver Cartridges - Explosive
	AMMO_REVOLVER_HIGH_VELOCITY = RAGE_JOAAT("AMMO_REVOLVER_HIGH_VELOCITY"), // Revolver Cartridges - High Velocity
	AMMO_REVOLVER_SPLIT_POINT = RAGE_JOAAT("AMMO_REVOLVER_SPLIT_POINT"), // Revolver Cartridges - Split Point
	AMMO_RIFLE = RAGE_JOAAT("AMMO_RIFLE"), // Rifle Cartridges - Regular
	AMMO_RIFLE_EXPRESS = RAGE_JOAAT("AMMO_RIFLE_EXPRESS"), // Rifle Cartridges - Express
	AMMO_RIFLE_EXPRESS_EXPLOSIVE = RAGE_JOAAT("AMMO_RIFLE_EXPRESS_EXPLOSIVE"), // Rifle Cartridges - Explosive
	AMMO_RIFLE_HIGH_VELOCITY = RAGE_JOAAT("AMMO_RIFLE_HIGH_VELOCITY"), // Rifle Cartridges - High Velocity
	AMMO_RIFLE_SPLIT_POINT = RAGE_JOAAT("AMMO_RIFLE_SPLIT_POINT"), // Rifle Cartridges - Split Point
	AMMO_SHOTGUN = RAGE_JOAAT("AMMO_SHOTGUN"), // Shotgun Shells - Regular
	AMMO_SHOTGUN_BUCKSHOT_INCENDIARY = RAGE_JOAAT("AMMO_SHOTGUN_BUCKSHOT_INCENDIARY"), // Shotgun Shells - Buckshot Incendiary
	AMMO_SHOTGUN_SLUG = RAGE_JOAAT("AMMO_SHOTGUN_SLUG"), // Shotgun - Slug
	AMMO_SHOTGUN_SLUG_EXPLOSIVE = RAGE_JOAAT("AMMO_SHOTGUN_SLUG_EXPLOSIVE"), // Shotgun Slugs - Explosive
	AMMO_THROWING_KNIVES = RAGE_JOAAT("AMMO_THROWING_KNIVES"), // Throwing Knife
	AMMO_THROWING_KNIVES_IMPROVED = RAGE_JOAAT("AMMO_THROWING_KNIVES_IMPROVED"), // Improved Throwing Knife
	AMMO_THROWING_KNIVES_POISON = RAGE_JOAAT("AMMO_THROWING_KNIVES_POISON"), // Poison Throwing Knife
	AMMO_TOMAHAWK = RAGE_JOAAT("AMMO_TOMAHAWK"), // Tomahawk
	AMMO_TOMAHAWK_ANCIENT = RAGE_JOAAT("AMMO_TOMAHAWK_ANCIENT"), // Ancient Tomahawk
	AMMO_TOMAHAWK_HOMING = RAGE_JOAAT("AMMO_TOMAHAWK_HOMING"), // Tomahawk - Homing
	AMMO_TOMAHAWK_IMPROVED = RAGE_JOAAT("AMMO_TOMAHAWK_IMPROVED"), // Tomahawk - Improved
};

enum eHorseModel : Hash
{
	A_C_HORSE_AMERICANPAINT_GREYOVERO = RAGE_JOAAT("A_C_HORSE_AMERICANPAINT_GREYOVERO"),
	A_C_HORSE_AMERICANPAINT_OVERO = RAGE_JOAAT("A_C_HORSE_AMERICANPAINT_OVERO"),
	A_C_HORSE_AMERICANPAINT_SPLASHEDWHITE = RAGE_JOAAT("A_C_HORSE_AMERICANPAINT_SPLASHEDWHITE"),
	A_C_HORSE_AMERICANPAINT_TOBIANO = RAGE_JOAAT("A_C_HORSE_AMERICANPAINT_TOBIANO"),
	A_C_HORSE_AMERICANSTANDARDBRED_BLACK = RAGE_JOAAT("A_C_HORSE_AMERICANSTANDARDBRED_BLACK"),
	A_C_HORSE_AMERICANSTANDARDBRED_BUCKSKIN = RAGE_JOAAT("A_C_HORSE_AMERICANSTANDARDBRED_BUCKSKIN"),
	A_C_HORSE_AMERICANSTANDARDBRED_PALOMINODAPPLE = RAGE_JOAAT("A_C_HORSE_AMERICANSTANDARDBRED_PALOMINODAPPLE"),
	A_C_HORSE_AMERICANSTANDARDBRED_SILVERTAILBUCKSKIN = RAGE_JOAAT("A_C_HORSE_AMERICANSTANDARDBRED_SILVERTAILBUCKSKIN"),
	A_C_HORSE_ANDALUSIAN_DARKBAY = RAGE_JOAAT("A_C_HORSE_ANDALUSIAN_DARKBAY"),
	A_C_HORSE_ANDALUSIAN_ROSEGRAY = RAGE_JOAAT("A_C_HORSE_ANDALUSIAN_ROSEGRAY"),
	A_C_HORSE_APPALOOSA_BLANKET = RAGE_JOAAT("A_C_HORSE_APPALOOSA_BLANKET"),
	A_C_HORSE_APPALOOSA_BROWNLEOPARD = RAGE_JOAAT("A_C_HORSE_APPALOOSA_BROWNLEOPARD"),
	A_C_HORSE_APPALOOSA_LEOPARD = RAGE_JOAAT("A_C_HORSE_APPALOOSA_LEOPARD"),
	A_C_HORSE_APPALOOSA_LEOPARDBLANKET = RAGE_JOAAT("A_C_HORSE_APPALOOSA_LEOPARDBLANKET"),
	A_C_HORSE_ARABIAN_BLACK = RAGE_JOAAT("A_C_HORSE_ARABIAN_BLACK"),
	A_C_HORSE_ARABIAN_ROSEGREYBAY = RAGE_JOAAT("A_C_HORSE_ARABIAN_ROSEGREYBAY"),
	A_C_HORSE_ARABIAN_WHITE = RAGE_JOAAT("A_C_HORSE_ARABIAN_WHITE"),
	A_C_HORSE_ARDENNES_BAYROAN = RAGE_JOAAT("A_C_HORSE_ARDENNES_BAYROAN"),
	A_C_HORSE_ARDENNES_STRAWBERRYROAN = RAGE_JOAAT("A_C_HORSE_ARDENNES_STRAWBERRYROAN"),
	A_C_HORSE_BELGIAN_BLONDCHESTNUT = RAGE_JOAAT("A_C_HORSE_BELGIAN_BLONDCHESTNUT"),
	A_C_HORSE_BELGIAN_MEALYCHESTNUT = RAGE_JOAAT("A_C_HORSE_BELGIAN_MEALYCHESTNUT"),
	A_C_HORSE_DUTCHWARMBLOOD_CHOCOLATEROAN = RAGE_JOAAT("A_C_HORSE_DUTCHWARMBLOOD_CHOCOLATEROAN"),
	A_C_HORSE_DUTCHWARMBLOOD_SEALBROWN = RAGE_JOAAT("A_C_HORSE_DUTCHWARMBLOOD_SEALBROWN"),
	A_C_HORSE_DUTCHWARMBLOOD_SOOTYBUCKSKIN = RAGE_JOAAT("A_C_HORSE_DUTCHWARMBLOOD_SOOTYBUCKSKIN"),
	A_C_HORSE_GANG_BILL = RAGE_JOAAT("A_C_HORSE_GANG_BILL"),
	A_C_HORSE_GANG_CHARLES = RAGE_JOAAT("A_C_HORSE_GANG_CHARLES"),
	A_C_HORSE_GANG_CHARLES_ENDLESSSUMMER = RAGE_JOAAT("A_C_HORSE_GANG_CHARLES_ENDLESSSUMMER"),
	A_C_HORSE_GANG_DUTCH = RAGE_JOAAT("A_C_HORSE_GANG_DUTCH"),
	A_C_HORSE_GANG_HOSEA = RAGE_JOAAT("A_C_HORSE_GANG_HOSEA"),
	A_C_HORSE_GANG_JAVIER = RAGE_JOAAT("A_C_HORSE_GANG_JAVIER"),
	A_C_HORSE_GANG_JOHN = RAGE_JOAAT("A_C_HORSE_GANG_JOHN"),
	A_C_HORSE_GANG_KAREN = RAGE_JOAAT("A_C_HORSE_GANG_KAREN"),
	A_C_HORSE_GANG_KIERAN = RAGE_JOAAT("A_C_HORSE_GANG_KIERAN"),
	A_C_HORSE_GANG_LENNY = RAGE_JOAAT("A_C_HORSE_GANG_LENNY"),
	A_C_HORSE_GANG_MICAH = RAGE_JOAAT("A_C_HORSE_GANG_MICAH"),
	A_C_HORSE_GANG_SADIE = RAGE_JOAAT("A_C_HORSE_GANG_SADIE"),
	A_C_HORSE_GANG_SADIE_ENDLESSSUMMER = RAGE_JOAAT("A_C_HORSE_GANG_SADIE_ENDLESSSUMMER"),
	A_C_HORSE_GANG_SEAN = RAGE_JOAAT("A_C_HORSE_GANG_SEAN"),
	A_C_HORSE_GANG_TRELAWNEY = RAGE_JOAAT("A_C_HORSE_GANG_TRELAWNEY"),
	A_C_HORSE_GANG_UNCLE = RAGE_JOAAT("A_C_HORSE_GANG_UNCLE"),
	A_C_HORSE_GANG_UNCLE_ENDLESSSUMMER = RAGE_JOAAT("A_C_HORSE_GANG_UNCLE_ENDLESSSUMMER"),
	A_C_HORSE_HUNGARIANHALFBRED_DARKDAPPLEGREY = RAGE_JOAAT("A_C_HORSE_HUNGARIANHALFBRED_DARKDAPPLEGREY"),
	A_C_HORSE_HUNGARIANHALFBRED_FLAXENCHESTNUT = RAGE_JOAAT("A_C_HORSE_HUNGARIANHALFBRED_FLAXENCHESTNUT"),
	A_C_HORSE_HUNGARIANHALFBRED_PIEBALDTOBIANO = RAGE_JOAAT("A_C_HORSE_HUNGARIANHALFBRED_PIEBALDTOBIANO"),
	A_C_HORSE_KENTUCKYSADDLE_BLACK = RAGE_JOAAT("A_C_HORSE_KENTUCKYSADDLE_BLACK"),
	A_C_HORSE_KENTUCKYSADDLE_CHESTNUTPINTO = RAGE_JOAAT("A_C_HORSE_KENTUCKYSADDLE_CHESTNUTPINTO"),
	A_C_HORSE_KENTUCKYSADDLE_GREY = RAGE_JOAAT("A_C_HORSE_KENTUCKYSADDLE_GREY"),
	A_C_HORSE_KENTUCKYSADDLE_SILVERBAY = RAGE_JOAAT("A_C_HORSE_KENTUCKYSADDLE_SILVERBAY"),
	A_C_HORSE_MISSOURIFOXTROTTER_AMBERCHAMPAGNE = RAGE_JOAAT("A_C_HORSE_MISSOURIFOXTROTTER_AMBERCHAMPAGNE"),
	A_C_HORSE_MISSOURIFOXTROTTER_SILVERDAPPLEPINTO = RAGE_JOAAT("A_C_HORSE_MISSOURIFOXTROTTER_SILVERDAPPLEPINTO"),
	A_C_HORSE_MORGAN_BAY = RAGE_JOAAT("A_C_HORSE_MORGAN_BAY"),
	A_C_HORSE_MORGAN_BAYROAN = RAGE_JOAAT("A_C_HORSE_MORGAN_BAYROAN"),
	A_C_HORSE_MORGAN_FLAXENCHESTNUT = RAGE_JOAAT("A_C_HORSE_MORGAN_FLAXENCHESTNUT"),
	A_C_HORSE_MORGAN_PALOMINO = RAGE_JOAAT("A_C_HORSE_MORGAN_PALOMINO"),
	A_C_HORSE_MUSTANG_GRULLODUN = RAGE_JOAAT("A_C_HORSE_MUSTANG_GRULLODUN"),
	A_C_HORSE_MUSTANG_TIGERSTRIPEDBAY = RAGE_JOAAT("A_C_HORSE_MUSTANG_TIGERSTRIPEDBAY"),
	A_C_HORSE_MUSTANG_WILDBAY = RAGE_JOAAT("A_C_HORSE_MUSTANG_WILDBAY"),
	A_C_HORSE_NOKOTA_BLUEROAN = RAGE_JOAAT("A_C_HORSE_NOKOTA_BLUEROAN"),
	A_C_HORSE_NOKOTA_REVERSEDAPPLEROAN = RAGE_JOAAT("A_C_HORSE_NOKOTA_REVERSEDAPPLEROAN"),
	A_C_HORSE_NOKOTA_WHITEROAN = RAGE_JOAAT("A_C_HORSE_NOKOTA_WHITEROAN"),
	A_C_HORSE_SHIRE_DARKBAY = RAGE_JOAAT("A_C_HORSE_SHIRE_DARKBAY"),
	A_C_HORSE_SHIRE_LIGHTGREY = RAGE_JOAAT("A_C_HORSE_SHIRE_LIGHTGREY"),
	A_C_HORSE_SUFFOLKPUNCH_REDCHESTNUT = RAGE_JOAAT("A_C_HORSE_SUFFOLKPUNCH_REDCHESTNUT"),
	A_C_HORSE_SUFFOLKPUNCH_SORREL = RAGE_JOAAT("A_C_HORSE_SUFFOLKPUNCH_SORREL"),
	A_C_HORSE_TENNESSEEWALKER_BLACKRABICANO = RAGE_JOAAT("A_C_HORSE_TENNESSEEWALKER_BLACKRABICANO"),
	A_C_HORSE_TENNESSEEWALKER_CHESTNUT = RAGE_JOAAT("A_C_HORSE_TENNESSEEWALKER_CHESTNUT"),
	A_C_HORSE_TENNESSEEWALKER_DAPPLEBAY = RAGE_JOAAT("A_C_HORSE_TENNESSEEWALKER_DAPPLEBAY"),
	A_C_HORSE_TENNESSEEWALKER_FLAXENROAN = RAGE_JOAAT("A_C_HORSE_TENNESSEEWALKER_FLAXENROAN"),
	A_C_HORSE_TENNESSEEWALKER_REDROAN = RAGE_JOAAT("A_C_HORSE_TENNESSEEWALKER_REDROAN"),
	A_C_HORSE_THOROUGHBRED_BLOODBAY = RAGE_JOAAT("A_C_HORSE_THOROUGHBRED_BLOODBAY"),
	A_C_HORSE_THOROUGHBRED_BRINDLE = RAGE_JOAAT("A_C_HORSE_THOROUGHBRED_BRINDLE"),
	A_C_HORSE_THOROUGHBRED_DAPPLEGREY = RAGE_JOAAT("A_C_HORSE_THOROUGHBRED_DAPPLEGREY"),
	A_C_HORSE_TURKOMAN_DARKBAY = RAGE_JOAAT("A_C_HORSE_TURKOMAN_DARKBAY"),
	A_C_HORSE_TURKOMAN_GOLD = RAGE_JOAAT("A_C_HORSE_TURKOMAN_GOLD"),
	A_C_HORSE_TURKOMAN_SILVER = RAGE_JOAAT("A_C_HORSE_TURKOMAN_SILVER"),
};

enum eVehicleModel : Hash
{
	ARMYSUPPLYWAGON = RAGE_JOAAT("ARMYSUPPLYWAGON"),
	CABOOSE01X = RAGE_JOAAT("CABOOSE01X"),
	GHOSTTRAINCABOOSE = RAGE_JOAAT("GHOSTTRAINCABOOSE"),
	GHOSTTRAINCOALCAR = RAGE_JOAAT("GHOSTTRAINCOALCAR"),
	GHOSTTRAINPASSENGER = RAGE_JOAAT("GHOSTTRAINPASSENGER"),
	GHOSTTRAINSTEAMER = RAGE_JOAAT("GHOSTTRAINSTEAMER"),
	NORTHCOALCAR01X = RAGE_JOAAT("NORTHCOALCAR01X"),
	STAGECOACH004X = RAGE_JOAAT("STAGECOACH004X"),
	STEAMERDUMMY = RAGE_JOAAT("STEAMERDUMMY"),
	TROLLEY01X = RAGE_JOAAT("TROLLEY01X"),
	TUGBOAT2 = RAGE_JOAAT("TUGBOAT2"),
	ARMOREDCAR01X = RAGE_JOAAT("ARMOREDCAR01X"),
	ARMOREDCAR03X = RAGE_JOAAT("ARMOREDCAR03X"),
	BOATSTEAM02X = RAGE_JOAAT("BOATSTEAM02X"),
	BREACH_CANNON = RAGE_JOAAT("BREACH_CANNON"),
	BUGGY03 = RAGE_JOAAT("BUGGY03"),
	CANOE = RAGE_JOAAT("CANOE"),
	CANOETREETRUNK = RAGE_JOAAT("CANOETREETRUNK"),
	CART01 = RAGE_JOAAT("CART01"),
	CART02 = RAGE_JOAAT("CART02"),
	CART03 = RAGE_JOAAT("CART03"),
	CART04 = RAGE_JOAAT("CART04"),
	CART05 = RAGE_JOAAT("CART05"),
	CART06 = RAGE_JOAAT("CART06"),
	CART07 = RAGE_JOAAT("CART07"),
	CART08 = RAGE_JOAAT("CART08"),
	CHUCKWAGON000X = RAGE_JOAAT("CHUCKWAGON000X"),
	CHUCKWAGON002X = RAGE_JOAAT("CHUCKWAGON002X"),
	COACH2 = RAGE_JOAAT("COACH2"),
	COACH3 = RAGE_JOAAT("COACH3"),
	COACH4 = RAGE_JOAAT("COACH4"),
	COACH5 = RAGE_JOAAT("COACH5"),
	COACH6 = RAGE_JOAAT("COACH6"),
	COALHOPPER01X = RAGE_JOAAT("COALHOPPER01X"),
	COAL_WAGON = RAGE_JOAAT("COAL_WAGON"),
	GATCHUCK = RAGE_JOAAT("GATCHUCK"),
	GATCHUCK_2 = RAGE_JOAAT("GATCHUCK_2"),
	GATLINGMAXIM02 = RAGE_JOAAT("GATLINGMAXIM02"),
	GATLING_GUN = RAGE_JOAAT("GATLING_GUN"),
	HANDCART = RAGE_JOAAT("HANDCART"),
	HORSEBOAT = RAGE_JOAAT("HORSEBOAT"),
	HOTAIRBALLOON01 = RAGE_JOAAT("HOTAIRBALLOON01"),
	HOTCHKISS_CANNON = RAGE_JOAAT("HOTCHKISS_CANNON"),
	KEELBOAT = RAGE_JOAAT("KEELBOAT"),
	LOGWAGON = RAGE_JOAAT("LOGWAGON"),
	LOGWAGON2 = RAGE_JOAAT("LOGWAGON2"),
	MIDLANDBOXCAR05X = RAGE_JOAAT("MIDLANDBOXCAR05X"),
	MIDLANDREFRIGERATORCAR = RAGE_JOAAT("MIDLANDREFRIGERATORCAR"),
	MINECART01X = RAGE_JOAAT("MINECART01X"),
	NORTHSTEAMER01X = RAGE_JOAAT("NORTHSTEAMER01X"),
	NORTHFLATCAR01X = RAGE_JOAAT("NORTHFLATCAR01X"),
	NORTHPASSENGER01X = RAGE_JOAAT("NORTHPASSENGER01X"),
	NORTHPASSENGER03X = RAGE_JOAAT("NORTHPASSENGER03X"),
	OILWAGON01X = RAGE_JOAAT("OILWAGON01X"),
	OILWAGON02X = RAGE_JOAAT("OILWAGON02X"),
	PIROGUE = RAGE_JOAAT("PIROGUE"),
	PIROGUE2 = RAGE_JOAAT("PIROGUE2"),
	POLICEWAGON01X = RAGE_JOAAT("POLICEWAGON01X"),
	POLICEWAGONGATLING01X = RAGE_JOAAT("POLICEWAGONGATLING01X"),
	PRIVATEARMOURED = RAGE_JOAAT("PRIVATEARMOURED"),
	PRIVATECOALCAR01X = RAGE_JOAAT("PRIVATECOALCAR01X"),
	PRIVATEDINING01X = RAGE_JOAAT("PRIVATEDINING01X"),
	PRIVATEOBSERVATIONCAR = RAGE_JOAAT("PRIVATEOBSERVATIONCAR"),
	PRIVATEROOMS01X = RAGE_JOAAT("PRIVATEROOMS01X"),
	PRIVATESTEAMER01X = RAGE_JOAAT("PRIVATESTEAMER01X"),
	PRIVATEBAGGAGE01X = RAGE_JOAAT("PRIVATEBAGGAGE01X"),
	PRIVATEBOXCAR01X = RAGE_JOAAT("PRIVATEBOXCAR01X"),
	PRIVATEBOXCAR02X = RAGE_JOAAT("PRIVATEBOXCAR02X"),
	PRIVATEBOXCAR04X = RAGE_JOAAT("PRIVATEBOXCAR04X"),
	PRIVATEFLATCAR01X = RAGE_JOAAT("PRIVATEFLATCAR01X"),
	PRIVATEOPENSLEEPER01X = RAGE_JOAAT("PRIVATEOPENSLEEPER01X"),
	PRIVATEOPENSLEEPER02X = RAGE_JOAAT("PRIVATEOPENSLEEPER02X"),
	PRIVATEPASSENGER01X = RAGE_JOAAT("PRIVATEPASSENGER01X"),
	RCBOAT = RAGE_JOAAT("RCBOAT"),
	ROWBOAT = RAGE_JOAAT("ROWBOAT"),
	ROWBOATSWAMP = RAGE_JOAAT("ROWBOATSWAMP"),
	ROWBOATSWAMP02 = RAGE_JOAAT("ROWBOATSWAMP02"),
	SHIP_GUAMA02 = RAGE_JOAAT("SHIP_GUAMA02"),
	SHIP_NBDGUAMA = RAGE_JOAAT("SHIP_NBDGUAMA"),
	SHIP_NBDGUAMA2 = RAGE_JOAAT("SHIP_NBDGUAMA2"),
	SKIFF = RAGE_JOAAT("SKIFF"),
	SMUGGLER02 = RAGE_JOAAT("SMUGGLER02"),
	STAGECOACH001X = RAGE_JOAAT("STAGECOACH001X"),
	STAGECOACH002X = RAGE_JOAAT("STAGECOACH002X"),
	STAGECOACH003X = RAGE_JOAAT("STAGECOACH003X"),
	STAGECOACH006X = RAGE_JOAAT("STAGECOACH006X"),
	TURBINEBOAT = RAGE_JOAAT("TURBINEBOAT"),
	UTILLIWAG = RAGE_JOAAT("UTILLIWAG"),
	WAGON02X = RAGE_JOAAT("WAGON02X"),
	WAGON03X = RAGE_JOAAT("WAGON03X"),
	WAGON04X = RAGE_JOAAT("WAGON04X"),
	WAGON05X = RAGE_JOAAT("WAGON05X"),
	WAGON06X = RAGE_JOAAT("WAGON06X"),
	WAGONCIRCUS01X = RAGE_JOAAT("WAGONCIRCUS01X"),
	WAGONCIRCUS02X = RAGE_JOAAT("WAGONCIRCUS02X"),
	WAGONDAIRY01X = RAGE_JOAAT("WAGONDAIRY01X"),
	WAGONDOC01X = RAGE_JOAAT("WAGONDOC01X"),
	WAGONPRISON01X = RAGE_JOAAT("WAGONPRISON01X"),
	WAGONTRAVELLER01X = RAGE_JOAAT("WAGONTRAVELLER01X"),
	WAGONWORK01X = RAGE_JOAAT("WAGONWORK01X"),
	WINTERSTEAMER = RAGE_JOAAT("WINTERSTEAMER"),
	WINTERCOALCAR = RAGE_JOAAT("WINTERCOALCAR"),
};

enum eSnowCoverageType
{
	Primary,
	Secondary,
	Xmas,
	XmasSecondary // since b1232
};
