#pragma once

#include "pch.h"
#include "rage/natives.h"
#include "rage/enums.h"

namespace Lists
{
	void Create();
}

inline std::map<std::string, Hash>
	g_VehicleList,
	g_ProvisionList,
	g_DocumentList,
	g_ConsumableList,
	g_PedList;

inline std::map<Hash, std::string>
	g_PedModelNameList,
	g_VehicleModelNameList;

constexpr inline std::array g_HerbList{
	HERB_ACUNAS_STAR_ORCHID,
	HERB_ALASKAN_GINSENG,
	HERB_AMERICAN_GINSENG,
	HERB_BAY_BOLETE,
	HERB_BLACK_BERRY,
	HERB_BLACK_CURRANT,
	HERB_BURDOCK_ROOT,
	HERB_CHANTERELLES,
	HERB_CIGAR_ORCHID,
	HERB_CLAMSHELL_ORCHID,
	HERB_COMMON_BULRUSH,
	HERB_CREEPING_THYME,
	HERB_DESERT_SAGE,
	HERB_DRAGONS_MOUTH_ORCHID,
	HERB_ENGLISH_MACE,
	HERB_EVERGREEN_HUCKLEBERRY,
	HERB_GHOST_ORCHID,
	HERB_GOLDEN_CURRANT,
	HERB_HARRIETUM_OFFICINALIS,
	HERB_HUMMINGBIRD_SAGE,
	HERB_INDIAN_TOBACCO,
	HERB_LADY_OF_NIGHT_ORCHID,
	HERB_LADY_SLIPPER_ORCHID,
	HERB_MILKWEED,
	HERB_MOCCASIN_FLOWER_ORCHID,
	HERB_NIGHT_SCENTED_ORCHID,
	HERB_OLEANDER_SAGE,
	HERB_OREGANO,
	HERB_PARASOL_MUSHROOM,
	HERB_PRAIRIE_POPPY,
	HERB_QUEENS_ORCHID,
	HERB_RAMS_HEAD,
	HERB_RAT_TAIL_ORCHID,
	HERB_RED_RASPBERRY,
	HERB_RED_SAGE,
	HERB_SPARROWS_EGG_ORCHID,
	HERB_SPIDER_ORCHID,
	HERB_VANILLA_FLOWER,
	HERB_VIOLET_SNOWDROP,
	HERB_WILD_CARROTS,
	HERB_WILD_FEVERFEW,
	HERB_WILD_MINT,
	HERB_WINTERGREEN_BERRY,
	HERB_YARROW,
};
